[package]
name = "ct-ta-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["serde_derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1.40"
