global:
  # the frequency with which data is pulled from CT, in sec
  ct_pull_frequency: 300
  # the frequency with which data is pushed to TA, in min
  # (NOTE: minimum frequency is 1min in TA, probably to reduce stress
  # on the CAN-Bus)
  ta_push_frequency: 2
  # which verbosity level should be logged?
  # allowed values are:
  # error
  # warn
  # info
  # debug
  # trace
  log_level: "debug"
  # Set the address to bind on when sending data to CMI
  emiter_bind_addr: "0.0.0.0"

rooms:
  # name of the room. must match occurances later on
  room1:
    # id of the ressource in CT.
    # this is used to actually map ressources to rooms
    churchtools_id: 41
    # The expected delta-T in K / h when this room is heating.
    # We use this value to calculate when to turn on heating.
    # in K/h, float
    delta_T_per_hour: 1.5
    # The target temperature for this room.
    # What temperature do we want to reach when the room is fully heated?
    # Will be used to calculate the required preheating time
    # in °C, float
    target_temperature: 20.0
    current_temperature:
      # we expect the current temperature to be sent from this CAN-ID
      receiving_can_id: 1
      # ... and from this PDO (as given in the GUI)
      receiving_pdo: 1
      # OPTION. DEFAULT 10.
      # When the current temperature for a room has been missing for at least ... minutes, stop waiting.
      # Instead, assume the current temperature to be `timeout_assume_temperature`.
      # NOTE: timeout values are up to 1m wrong, since the status is updated once a minute in some cases (when we do not receive any packets).
      #
      # In min
      timeout: 5
      # OPTION
      # When we do not receive a current temperature, use this assumed temperature to calculate preheating times.
      # When this is not given, the global_assume_current_temperature_offset is used (see below)
      timeout_assume_temperature: 16
  room6:
    churchtools_id: 42
    delta_T_per_hour: 1.5
    target_temperature: 20
    current_temperature:
      receiving_can_id: 2
      receiving_pdo: 1
  room2:
    churchtools_id: 56
    delta_T_per_hour: 1.5
    target_temperature: 20
    current_temperature:
      receiving_can_id: 3
      receiving_pdo: 1


# define any number of cmis to which to send data
cmis:
    # hostname or ip
  - host: hostname.example.com
    # virtual can id to use on that CMIs CAN-Bus
    our_virtual_can_id: 59
    # rooms to push data for to this bus
    rooms:
    - name: room1
      # the output index to send this value from on the CAN Bus
      pdo_index: 1
    - name: room6
      pdo_index: 2
  - host: 10.15.6.6
    our_virtual_can_id: 12
    rooms:
    # notice that rooms can be overlapping
    # here, the data for room 1 is sent to both the CMI at hostname.example.com and at 10.15.6.6
    # but to different pdo_indices in the CAN network
    - name: room1
      pdo_index: 8
    - name: room2
      pdo_index: 2

# we scale hold over time based on external temperature
# For this, we need a sensor. We expect to get the external temperature via COE
current_temperature:
  # OUR bind address. Sending CMI will need to send the external temperature to this address with COEv2
  # Port 5442/UDP NEEDs to be free on this address - CMIs cannot send COEv2 on different ports.
  bind_addr: 192.168.24.173
  # When
  # - A rooms current temperature is in timeout
  # - The room definition in this file has no timeout_assume_temperature
  # Instead assume the current temperature to be `room.target_temperature - global_assume_current_temperature_offset`.
  # In K
  global_assume_current_temperature_offset: 4

ct:
  # the hostname of your CT instance
  host: "example.church.tools"
  # The login token for the user to use
  # user needs read-access to the ressources defined above
  login_token: "NOT_THE_LOGIN_TOKEN"

